export const CoffeesUtils = [
    {
        id: '1',
        title: 'Expresso Tradicional',
        description: 'O tradicional café feito com água quente e grãos moídos',
        features: ['Tradicional'],
        image: 'expresso',
        price: 9.90,
        quantity: 1,
    },
    {
        id: '2',
        title: 'Expresso Americano',
        description: 'Expresso diluído, menos intenso que o tradicional',
        features: ['Tradicional'],
        image: 'americano',
        price: 20,
        quantity: 1,
    },
    {
        id: '3',
        title: 'Expresso Cremoso',
        description: 'Café expresso tradicional com espuma cremosa',
        features: ['Tradicional'],
        image: 'expresso-cremoso',
        price: 22,
        quantity: 1,
    },
    {
        id: '4',
        title: 'Expresso Gelado',
        description: 'Bebida preparada com café expresso e cubos de gelo',
        features: ['Tradicional', 'gelado'],
        image: 'cafe-gelado',
        price: 24.50,
        quantity: 1,
    },
    {
        id: '5',
        title: 'Café com Leite',
        description: 'Meio a meio de expresso tradicional com leite vaporizado',
        features: ['Tradicional', 'com leite'],
        image: 'cafe-leite',
        price: 9.90,
        quantity: 1,
    },
    {
        id: '6',
        title: 'Latte',
        description: 'Uma dose de café expresso com o dobro de leite e espuma cremosa',
        features: ['Tradicional', 'com leite'],
        image: 'latte',
        price: 19.80,
        quantity: 1,
    },
    {
        id: '7',
        title: 'Capuccino',
        description: 'Bebida com canela feita de doses iguais de café, leite e espuma',
        features: ['Tradicional', 'com leite'],
        image: 'capuccino',
        price: 18.90,
        quantity: 1,
    },
    {
        id: '8',
        title: 'Macchiato',
        description: 'Café expresso misturado com um pouco de leite quente e espuma',
        features: ['Tradicional', 'com leite'],
        image: 'macchiato',
        price: 23,
        quantity: 1,
    },
    {
        id: '9',
        title: 'Mocaccino',
        description: 'Café expresso com calda de chocolate, pouco leite e espuma',
        features: ['Tradicional', 'com leite'],
        image: 'mochaccino',
        price: 24,
        quantity: 1,
    },
    {
        id: '10',
        title: 'Chocolate Quente',
        description: 'Bebida feita com chocolate dissolvido no leite quente e café',
        features: ['Especial', 'com leite'],
        image: 'chocolate-quente',
        price: 15,
        quantity: 1,
    },
    {
        id: '11',
        title: 'Cubano',
        description: 'Drink gelado de café expresso com rum, creme de leite e hortelã',
        features: ['Especial', 'alcoólico', 'Gelado'],
        image: 'cubano',
        price: 25,
        quantity: 1,
    },
    {
        id: '12',
        title: 'Havaiano',
        description: 'Bebida adocicada preparada com café e leite de coco',
        features: ['Especial'],
        image: 'havaiano',
        price: 20,
        quantity: 1,
    },
    {
        id: '13',
        title: 'Árabe',
        description: 'Bebida preparada com grãos de café árabe e especiarias',
        features: ['Especial'],
        image: 'arabe',
        price: 14.90,
        quantity: 1,
    },
    {
        id: '14',
        title: 'Irlandês',
        description: 'Bebida a base de café, uísque irlandês, açúcar e chantilly',
        features: ['Especial', 'alcoólico'],
        image: 'irlandes',
        price: 18.90,
        quantity: 1,
    },
]